os: linux
language: node_js
node_js:
  - "8"
install: yarn
scripts:
  - yarn workspace @light0x00/parser-generator run test
  - yarn workspace @light0x00/parser run test
notifications:
  email:
    recipients:
      - light0x00@163.com
    on_success: change
    on_failure: always

